# list_conditions = [{'count_same_stickers': 4, 'price_stickers': 2, 'self_price': 0.8},
#                    {'count_same_stickers': 4, 'price_stickers': 4, 'self_price': 4},
#                    # {'count_same_stickers': 4, 'price_stickers': 10, 'self_price': 100},
#                    {'count_same_stickers': 3, 'price_stickers': 1.5, 'self_price': 0.8},
#                    {'count_same_stickers': 3, 'price_stickers': 5, 'self_price': 4},
#                    # {'count_same_stickers': 3, 'price_stickers': 10, 'self_price': 100},
#                    {'count_same_stickers': 2, 'price_stickers': 1.5, 'self_price': 0.8},
#                    {'count_same_stickers': 2, 'price_stickers': 6, 'self_price': 4},
#                    # {'count_same_stickers': 2, 'price_stickers': 10, 'self_price': 100},
#                    {'count_same_stickers': 1, 'price_stickers': 5, 'self_price': 0.8},
#                    {'count_same_stickers': 1, 'price_stickers': 15, 'self_price': 20},
#                    # {'count_same_stickers': 1, 'price_stickers': 20, 'self_price': 100}
#                    ]
list_conditions = [{'count_same_stickers': 4, 'price_stickers': 2, 'self_price': 0.8},
                   {'count_same_stickers': 4, 'price_stickers': 4, 'self_price': 4},
                   # {'count_same_stickers': 4, 'price_stickers': 10, 'self_price': 100},
                   {'count_same_stickers': 3, 'price_stickers': 1.5, 'self_price': 0.8},
                   {'count_same_stickers': 3, 'price_stickers': 5, 'self_price': 4},
                   # {'count_same_stickers': 3, 'price_stickers': 10, 'self_price': 100},
                   {'count_same_stickers': 2, 'price_stickers': 1.5, 'self_price': 0.8},
                   {'count_same_stickers': 2, 'price_stickers': 6, 'self_price': 4},
                   # {'count_same_stickers': 2, 'price_stickers': 10, 'self_price': 100},
                   {'count_same_stickers': 1, 'price_stickers': 5, 'self_price': 0.8},
                   {'count_same_stickers': 1, 'price_stickers': 10, 'self_price': 4},
                   # {'count_same_stickers': 1, 'price_stickers': 15, 'self_price': 20},
                   # {'count_same_stickers': 1, 'price_stickers': 20, 'self_price': 100}
                   ]
